/* Autogenerated by /home/user/linuxcnc/bin/halcompile on Sat Nov 19 19:07:44 2022 -- do not edit */
#include "rtapi.h"
#ifdef RTAPI
#include "rtapi_app.h"
#endif
#include "rtapi_string.h"
#include "rtapi_errno.h"
#include "hal.h"
#include "rtapi_math64.h"

static int comp_id;

#ifdef MODULE_INFO
MODULE_INFO(linuxcnc, "component:tp:IEC TP timer - generate a high pulse of defined duration on rising edge");
MODULE_INFO(linuxcnc, "pin:in:bit:0:in:Input signal:None:None");
MODULE_INFO(linuxcnc, "pin:q:bit:0:out:Output signal:None:None");
MODULE_INFO(linuxcnc, "pin:et:float:0:out:Elapsed time since start of pulse in seconds:None:None");
MODULE_INFO(linuxcnc, "param:pt:float:0:rw:Pulse time in seconds:None:None");
MODULE_INFO(linuxcnc, "funct:_:1:Update the timer");
MODULE_INFO(linuxcnc, "license:GPL");
MODULE_INFO(linuxcnc, "author:Chad Woitas");
MODULE_LICENSE("GPL");
#endif // MODULE_INFO


struct __comp_state {
    struct __comp_state *_next;
    hal_bit_t *in;
    hal_bit_t *q;
    hal_float_t *et;
    hal_float_t pt;
    int in_old;

};
struct __comp_state *__comp_first_inst=0, *__comp_last_inst=0;

static void _(struct __comp_state *__comp_inst, long period);
static int __comp_get_data_size(void);
#undef TRUE
#define TRUE (1)
#undef FALSE
#define FALSE (0)
#undef true
#define true (1)
#undef false
#define false (0)

static int export(char *prefix, long extra_arg) {
    char buf[HAL_NAME_LEN + 1];
    int r = 0;
    int sz = sizeof(struct __comp_state) + __comp_get_data_size();
    struct __comp_state *inst = hal_malloc(sz);
    memset(inst, 0, sz);
    r = hal_pin_bit_newf(HAL_IN, &(inst->in), comp_id,
        "%s.in", prefix);
    if(r != 0) return r;
    r = hal_pin_bit_newf(HAL_OUT, &(inst->q), comp_id,
        "%s.q", prefix);
    if(r != 0) return r;
    r = hal_pin_float_newf(HAL_OUT, &(inst->et), comp_id,
        "%s.et", prefix);
    if(r != 0) return r;
    r = hal_param_float_newf(HAL_RW, &(inst->pt), comp_id,
        "%s.pt", prefix);
    if(r != 0) return r;
    rtapi_snprintf(buf, sizeof(buf), "%s", prefix);
    r = hal_export_funct(buf, (void(*)(void *inst, long))_, inst, 1, 0, comp_id);
    if(r != 0) return r;
    if(__comp_last_inst) __comp_last_inst->_next = inst;
    __comp_last_inst = inst;
    if(!__comp_first_inst) __comp_first_inst = inst;
    return 0;
}
static int default_count=1, count=0;
RTAPI_MP_INT(count, "number of tp");
char *names = ""; // comma separated names
RTAPI_MP_STRING(names, "names of tp");
int rtapi_app_main(void) {
    int r = 0;
    int i;
    comp_id = hal_init("tp");
    if(comp_id < 0) return comp_id;
    if(count && names[0]) {
        rtapi_print_msg(RTAPI_MSG_ERR,"count= and names= are mutually exclusive\n");
        return -EINVAL;
    }
    if(!count && !names[0]) count = default_count;
    if(count) {
        for(i=0; i<count; i++) {
            char buf[HAL_NAME_LEN + 1];
            rtapi_snprintf(buf, sizeof(buf), "tp.%d", i);
            r = export(buf, i);
            if(r != 0) break;
       }
    } else {
        size_t i, j;
        int idx;
        char buf[HAL_NAME_LEN+1];
        const size_t length = strlen(names);
        for (i = j = idx = 0; i <= length; i++) {
            const char c = buf[j] = names[i];
            if ((c == ',') || (c == '\0')) {
                buf[j] = '\0';
                r = export(buf, idx);
                if(r != 0) {break;}
                idx++;
                j = 0;
            } else {
                if (++j == (sizeof(buf) / sizeof(buf[0]))) {
                    buf[j - 1] = '\0';
                    rtapi_print_msg(RTAPI_MSG_ERR,"names: \"%s\" too long\n", buf);
                    r = -EINVAL;
                    break;
                }
            }
        }
    }
    if(r) {
        hal_exit(comp_id);
    } else {
        hal_ready(comp_id);
    }
    return r;
}

void rtapi_app_exit(void) {
    hal_exit(comp_id);
}

#undef FUNCTION
#define FUNCTION(name) static void name(struct __comp_state *__comp_inst, long period)
#undef EXTRA_SETUP
#define EXTRA_SETUP() static int extra_setup(struct __comp_state *__comp_inst, char *prefix, long extra_arg)
#undef EXTRA_CLEANUP
#define EXTRA_CLEANUP() static void extra_cleanup(void)
#undef fperiod
#define fperiod (period * 1e-9)
#undef in
#define in (0+*__comp_inst->in)
#undef q
#define q (*__comp_inst->q)
#undef et
#define et (*__comp_inst->et)
#undef pt
#define pt (__comp_inst->pt)
#undef in_old
#define in_old (__comp_inst->in_old)


#line 33 "/home/user/linuxcnc/src/hal/components/tp.comp"
FUNCTION(_) {
        if(pt < 0) {
            pt = 0;
            rtapi_print_msg(RTAPI_MSG_WARN,
                            "tp: Pulse time must be positive, resetting to 0");
        }
        if(et < 0) {
            et = 0;
            rtapi_print_msg(RTAPI_MSG_WARN,
                            "tp: Elapsed time rolled over, resetting to 0");
        }

        // Check timers
        if((in && !in_old) || q){
            // Update outputs
            if(et < pt){
                q = 1;
                et += fperiod;
            }
            else{
                q = 0;
            }
        }
        else{
            // Reset Variables
            et = 0;
            q = 0;
        }
        in_old = in;
}

static int __comp_get_data_size(void) { return 0; }
