#!/bin/bash
cd ../../../

cd scripts 
./halrun -U
. ./rip-environment 

halcmd stop
halcmd loadrt threads name1=base-thread fp1=0 period1=25000 name2=servo-thread period2=1000000
halcmd loadrt scurve
halcmd addf scurve_update servo-thread
halcmd start
halcmd show
